CREATE DATABASE StandManagement
USE StandManagement
CREATE TABLE Cars (Id int IDENTITY NOT NULL, PlateNumber varchar(255) NOT NULL, Price float(10) NOT NULL, ModelId int NOT NULL, PRIMARY KEY (Id));
CREATE TABLE Users (Id int IDENTITY NOT NULL, Username varchar(255) NOT NULL, Password varchar(255) NOT NULL, PRIMARY KEY (Id));
CREATE TABLE Sells (Id int IDENTITY NOT NULL, UserId int NOT NULL, CarId int NOT NULL, PRIMARY KEY (Id));
CREATE TABLE Brands (Id int IDENTITY NOT NULL, Name varchar(255) NOT NULL, PRIMARY KEY (Id));
CREATE TABLE Models (Id int IDENTITY NOT NULL, Name varchar(255) NOT NULL, BrandId int NOT NULL, PRIMARY KEY (Id));
ALTER TABLE Models ADD CONSTRAINT FKModels257002 FOREIGN KEY (BrandId) REFERENCES Brands (Id);
ALTER TABLE Cars ADD CONSTRAINT FKCars773524 FOREIGN KEY (ModelId) REFERENCES Models (Id);
ALTER TABLE Sells ADD CONSTRAINT FKSells368620 FOREIGN KEY (UserId) REFERENCES Users (Id);
ALTER TABLE Sells ADD CONSTRAINT FKSells741308 FOREIGN KEY (CarId) REFERENCES Cars (Id);
